[package]
name = "hub"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = { version = "0.7", features = ["ws"] }
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
models = { path = "../models" }
chrono = { version = "0.4", default-features = false, features = ["clock"] }
futures = "0.3"
rsa = { version = "0.9", default-features = false, features = ["pem"] }
base64 = "0.22"
tower-http = { version = "0.5", features = ["cors"] }
hex = "0.4.3"
axum-server = { version = "0.6", features = ["tls-rustls"] }
dashmap = "5"
hmac = "0.12"
sha2 = "0.10"
jsonwebtoken = { version = "9", default-features = false, features = ["use_pem"] }
http = "1"
tokio-tungstenite = { version = "0.24", features = ["deflate"] }
tungstenite = { version = "0.24", features = ["deflate"] }
