#!/usr/bin/env python3
"""
Secret Rotation Script for TetraCore Hub
Автоматична ротація секретів з підтримкою різних провайдерів
"""

import os
import sys
import json
import secrets
import string
import argparse
import subprocess
from datetime import datetime, timezone
from pathlib import Path
from typing import Dict, List, Optional, Tuple, Any
import base64
import hashlib
import hmac

try:
    import boto3
    HAS_AWS = True
except ImportError:
    HAS_AWS = False

try:
    import hvac
    HAS_VAULT = True
except ImportError:
    HAS_VAULT = False

try:
    from cryptography.fernet import Fernet
    from cryptography.hazmat.primitives import hashes
    from cryptography.hazmat.primitives.kdf.pbkdf2 import PBKDF2HMAC
    HAS_CRYPTO = True
except ImportError:
    HAS_CRYPTO = False

import structlog

# Налаштування логування
logger = structlog.get_logger()

# Константи
BACKUP_DIR = Path(__file__).parent.parent / "secrets_backup"
CONFIG_FILE = Path(__file__).parent.parent / ".secrets_config.json"
ROTATION_LOG = Path(__file__).parent.parent / "logs" / "secret_rotation.log"

# Типи секретів
SECRET_TYPES = {
    "jwt_secret": {"length": 64, "chars": string.ascii_letters + string.digits},
    "api_key": {"length": 32, "chars": string.ascii_letters + string.digits},
    "password": {"length": 24, "chars": string.ascii_letters + string.digits + "!@#$%^&*"},
    "encryption_key": {"length": 32, "chars": None},  # Binary key
    "token": {"length": 48, "chars": string.ascii_letters + string.digits},
    "webhook_secret": {"length": 32, "chars": string.ascii_letters + string.digits},
}

# Список критичних секретів для ротації
CRITICAL_SECRETS = [
    "JWT_SECRET",
    "ADMIN_PASSWORD",
    "REDIS_PASSWORD",
    "ENCRYPTION_KEY",
    "API_SECRET_KEY",
    "BOT_TOKEN_PROD",
    "BOT_TOKEN_DEV",
    "API_ID",
    "API_HASH",
    "AWS_ACCESS_KEY_ID",
    "AWS_SECRET_ACCESS_KEY",
    "WEBHOOK_SECRET",
    "SESSION_SECRET"
]


class SecretProvider:
    """Базовий клас для провайдерів секретів"""

    def get_secret(self, key: str) -> Optional[str]:
        """Отримати секрет"""
        raise NotImplementedError

    def set_secret(self, key: str, value: str) -> bool:
        """Встановити секрет"""
        raise NotImplementedError

    def delete_secret(self, key: str) -> bool:
        """Видалити секрет"""
        raise NotImplementedError

    def list_secrets(self) -> List[str]:
        """Список всіх секретів"""
        raise NotImplementedError


class EnvFileProvider(SecretProvider):
    """Провайдер для .env файлів (для локальної розробки)"""

    def __init__(self, env_file: Path):
        self.env_file = env_file
        self.secrets = self._load_env()

    def _load_env(self) -> Dict[str, str]:
        """Завантажити секрети з .env файлу"""
        secrets = {}
        if self.env_file.exists():
            with open(self.env_file, 'r') as f:
                for line in f:
                    line = line.strip()
                    if line and not line.startswith('#') and '=' in line:
                        key, value = line.split('=', 1)
                        secrets[key.strip()] = value.strip().strip('"\'')
        return secrets

    def _save_env(self):
        """Зберегти секрети в .env файл"""
        with open(self.env_file, 'w') as f:
            f.write("# Auto-generated by rotate_secrets.py\n")
            f.write(f"# Generated at: {datetime.now(timezone.utc).isoformat()}\n\n")
            for key, value in sorted(self.secrets.items()):
                f.write(f"{key}={value}\n")

    def get_secret(self, key: str) -> Optional[str]:
        return self.secrets.get(key)

    def set_secret(self, key: str, value: str) -> bool:
        self.secrets[key] = value
        self._save_env()
        return True

    def delete_secret(self, key: str) -> bool:
        if key in self.secrets:
            del self.secrets[key]
            self._save_env()
            return True
        return False

    def list_secrets(self) -> List[str]:
        return list(self.secrets.keys())


class AWSSecretsProvider(SecretProvider):
    """AWS Secrets Manager провайдер"""

    def __init__(self, region: str = "us-east-1", prefix: str = "tetracore/"):
        if not HAS_AWS:
            raise ImportError("boto3 не встановлено. Виконайте: pip install boto3")
        self.client = boto3.client('secretsmanager', region_name=region)
        self.prefix = prefix

    def get_secret(self, key: str) -> Optional[str]:
        try:
            response = self.client.get_secret_value(SecretId=f"{self.prefix}{key}")
            return response['SecretString']
        except self.client.exceptions.ResourceNotFoundException:
            return None
        except Exception as e:
            logger.error(f"AWS Secrets Manager error: {e}")
            return None

    def set_secret(self, key: str, value: str) -> bool:
        try:
            secret_id = f"{self.prefix}{key}"
            try:
                # Спробувати оновити існуючий секрет
                self.client.update_secret(SecretId=secret_id, SecretString=value)
            except self.client.exceptions.ResourceNotFoundException:
                # Створити новий секрет
                self.client.create_secret(Name=secret_id, SecretString=value)
            return True
        except Exception as e:
            logger.error(f"AWS Secrets Manager error: {e}")
            return False

    def delete_secret(self, key: str) -> bool:
        try:
            self.client.delete_secret(
                SecretId=f"{self.prefix}{key}",
                ForceDeleteWithoutRecovery=False
            )
            return True
        except Exception as e:
            logger.error(f"AWS Secrets Manager error: {e}")
            return False

    def list_secrets(self) -> List[str]:
        try:
            secrets = []
            paginator = self.client.get_paginator('list_secrets')
            for page in paginator.paginate():
                for secret in page['SecretList']:
                    if secret['Name'].startswith(self.prefix):
                        secret_name = secret['Name'][len(self.prefix):]
                        secrets.append(secret_name)
            return secrets
        except Exception as e:
            logger.error(f"AWS Secrets Manager error: {e}")
            return []


class HashiCorpVaultProvider(SecretProvider):
    """HashiCorp Vault провайдер"""

    def __init__(self, url: str, token: str, mount_point: str = "secret"):
        if not HAS_VAULT:
            raise ImportError("hvac не встановлено. Виконайте: pip install hvac")
        self.client = hvac.Client(url=url, token=token)
        self.mount_point = mount_point

    def get_secret(self, key: str) -> Optional[str]:
        try:
            response = self.client.secrets.kv.v2.read_secret_version(
                path=key,
                mount_point=self.mount_point
            )
            return response['data']['data'].get('value')
        except Exception as e:
            logger.error(f"Vault error: {e}")
            return None

    def set_secret(self, key: str, value: str) -> bool:
        try:
            self.client.secrets.kv.v2.create_or_update_secret(
                path=key,
                secret={'value': value},
                mount_point=self.mount_point
            )
            return True
        except Exception as e:
            logger.error(f"Vault error: {e}")
            return False

    def delete_secret(self, key: str) -> bool:
        try:
            self.client.secrets.kv.v2.delete_metadata_and_all_versions(
                path=key,
                mount_point=self.mount_point
            )
            return True
        except Exception as e:
            logger.error(f"Vault error: {e}")
            return False

    def list_secrets(self) -> List[str]:
        try:
            response = self.client.secrets.kv.v2.list_secrets(
                mount_point=self.mount_point
            )
            return response['data']['keys']
        except Exception as e:
            logger.error(f"Vault error: {e}")
            return []


class SecretRotator:
    """Основний клас для ротації секретів"""

    def __init__(self, provider: SecretProvider):
        self.provider = provider
        self.backup_dir = BACKUP_DIR
        self.backup_dir.mkdir(exist_ok=True)

        # Створити директорію для логів
        ROTATION_LOG.parent.mkdir(exist_ok=True)

    def generate_secret(self, secret_type: str = "api_key") -> str:
        """Генерувати новий секрет"""
        config = SECRET_TYPES.get(secret_type, SECRET_TYPES["api_key"])

        if secret_type == "encryption_key":
            # Генерувати бінарний ключ для шифрування
            if HAS_CRYPTO:
                return Fernet.generate_key().decode('utf-8')
            else:
                # Fallback для генерації ключа
                return base64.urlsafe_b64encode(
                    secrets.token_bytes(32)
                ).decode('utf-8')

        length = config["length"]
        chars = config["chars"]
        return ''.join(secrets.choice(chars) for _ in range(length))

    def backup_secret(self, key: str, value: str):
        """Створити резервну копію секрету"""
        timestamp = datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")
        backup_file = self.backup_dir / f"{key}_{timestamp}.bak"

        # Зашифрувати backup якщо можливо
        if HAS_CRYPTO and os.getenv("BACKUP_ENCRYPTION_KEY"):
            fernet = Fernet(os.getenv("BACKUP_ENCRYPTION_KEY").encode())
            encrypted_value = fernet.encrypt(value.encode())
            backup_data = {
                "key": key,
                "value": base64.b64encode(encrypted_value).decode('utf-8'),
                "encrypted": True,
                "timestamp": timestamp
            }
        else:
            # Хешувати значення для безпеки
            hashed_value = hashlib.sha256(value.encode()).hexdigest()
            backup_data = {
                "key": key,
                "value_hash": hashed_value,
                "encrypted": False,
                "timestamp": timestamp,
                "warning": "Value not stored - only hash available"
            }

        with open(backup_file, 'w') as f:
            json.dump(backup_data, f, indent=2)

        logger.info(f"Backup created: {backup_file}")

    def rotate_secret(self, key: str, secret_type: str = "api_key",
                     custom_value: Optional[str] = None) -> Tuple[bool, str]:
        """Ротувати один секрет"""
        try:
            # Отримати старе значення для backup
            old_value = self.provider.get_secret(key)
            if old_value:
                self.backup_secret(key, old_value)

            # Генерувати або використати нове значення
            new_value = custom_value or self.generate_secret(secret_type)

            # Встановити нове значення
            success = self.provider.set_secret(key, new_value)

            if success:
                self._log_rotation(key, "SUCCESS")
                return True, new_value
            else:
                self._log_rotation(key, "FAILED")
                return False, ""

        except Exception as e:
            logger.error(f"Error rotating {key}: {e}")
            self._log_rotation(key, "ERROR", str(e))
            return False, ""

    def rotate_all_critical(self) -> Dict[str, bool]:
        """Ротувати всі критичні секрети"""
        results = {}

        # Визначити типи для кожного секрету
        secret_types_map = {
            "JWT_SECRET": "jwt_secret",
            "ADMIN_PASSWORD": "password",
            "REDIS_PASSWORD": "password",
            "ENCRYPTION_KEY": "encryption_key",
            "API_SECRET_KEY": "api_key",
            "BOT_TOKEN_PROD": "token",
            "BOT_TOKEN_DEV": "token",
            "API_ID": "api_key",
            "API_HASH": "api_key",
            "AWS_ACCESS_KEY_ID": "api_key",
            "AWS_SECRET_ACCESS_KEY": "api_key",
            "WEBHOOK_SECRET": "webhook_secret",
            "SESSION_SECRET": "jwt_secret"
        }

        for secret_key in CRITICAL_SECRETS:
            secret_type = secret_types_map.get(secret_key, "api_key")
            success, _ = self.rotate_secret(secret_key, secret_type)
            results[secret_key] = success

        return results

    def verify_rotation(self, key: str, old_value: str) -> bool:
        """Перевірити що ротація пройшла успішно"""
        new_value = self.provider.get_secret(key)
        return new_value is not None and new_value != old_value

    def _log_rotation(self, key: str, status: str, error: str = ""):
        """Логувати операцію ротації"""
        log_entry = {
            "timestamp": datetime.now(timezone.utc).isoformat(),
            "key": key,
            "status": status,
            "error": error
        }

        with open(ROTATION_LOG, 'a') as f:
            f.write(json.dumps(log_entry) + "\n")


def get_provider(provider_type: str) -> SecretProvider:
    """Отримати провайдер за типом"""
    if provider_type == "env":
        env_file = Path(__file__).parent.parent / ".env"
        return EnvFileProvider(env_file)

    elif provider_type == "aws":
        region = os.getenv("AWS_REGION", "us-east-1")
        prefix = os.getenv("AWS_SECRETS_PREFIX", "tetracore/")
        return AWSSecretsProvider(region, prefix)

    elif provider_type == "vault":
        url = os.getenv("VAULT_URL", "http://localhost:8200")
        token = os.getenv("VAULT_TOKEN")
        if not token:
            raise ValueError("VAULT_TOKEN не встановлено")
        return HashiCorpVaultProvider(url, token)

    else:
        raise ValueError(f"Невідомий тип провайдера: {provider_type}")


def main():
    parser = argparse.ArgumentParser(description="Ротація секретів TetraCore Hub")
    parser.add_argument(
        "--provider",
        choices=["env", "aws", "vault"],
        default="env",
        help="Провайдер для зберігання секретів"
    )
    parser.add_argument(
        "--rotate-all",
        action="store_true",
        help="Ротувати всі критичні секрети"
    )
    parser.add_argument(
        "--rotate-key",
        help="Ротувати конкретний ключ"
    )
    parser.add_argument(
        "--secret-type",
        choices=list(SECRET_TYPES.keys()),
        default="api_key",
        help="Тип секрету для генерації"
    )
    parser.add_argument(
        "--list",
        action="store_true",
        help="Показати список всіх секретів"
    )
    parser.add_argument(
        "--verify",
        help="Перевірити що ключ був змінений"
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Показати що буде зроблено без виконання"
    )

    args = parser.parse_args()

    try:
        # Отримати провайдер
        provider = get_provider(args.provider)
        rotator = SecretRotator(provider)

        if args.list:
            # Показати список секретів
            secrets = provider.list_secrets()
            print("Доступні секрети:")
            for secret in sorted(secrets):
                print(f"  - {secret}")

        elif args.rotate_all:
            # Ротувати всі критичні секрети
            if args.dry_run:
                print("DRY RUN: Будуть ротовані наступні секрети:")
                for key in CRITICAL_SECRETS:
                    print(f"  - {key}")
            else:
                print("Ротація критичних секретів...")
                results = rotator.rotate_all_critical()

                print("\nРезультати ротації:")
                for key, success in results.items():
                    status = "✓" if success else "✗"
                    print(f"  {status} {key}")

                # Показати підсумок
                successful = sum(1 for s in results.values() if s)
                total = len(results)
                print(f"\nУспішно ротовано: {successful}/{total}")

                if successful < total:
                    sys.exit(1)

        elif args.rotate_key:
            # Ротувати конкретний ключ
            if args.dry_run:
                print(f"DRY RUN: Буде ротовано ключ '{args.rotate_key}'")
                new_value = rotator.generate_secret(args.secret_type)
                print(f"Приклад нового значення: {new_value[:8]}...")
            else:
                print(f"Ротація ключа '{args.rotate_key}'...")
                success, new_value = rotator.rotate_secret(
                    args.rotate_key,
                    args.secret_type
                )

                if success:
                    print(f"✓ Ключ успішно ротовано")
                    print(f"Нове значення: {new_value[:8]}...")
                else:
                    print(f"✗ Помилка ротації ключа")
                    sys.exit(1)

        elif args.verify:
            # Перевірити ротацію
            old_value = input("Введіть старе значення для перевірки: ")
            if rotator.verify_rotation(args.verify, old_value):
                print("✓ Ротація підтверджена - значення змінено")
            else:
                print("✗ Ротація не підтверджена")
                sys.exit(1)

        else:
            parser.print_help()

    except Exception as e:
        logger.error(f"Помилка: {e}")
        print(f"✗ Помилка: {e}")
        sys.exit(1)


if __name__ == "__main__":
    main()
