// Package secrets provides secret management and rotation for TetraCore Hub.
package secrets

import (
	"bufio"
	"context"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"
)

// Provider defines the interface for secret storage providers.
type Provider interface {
	// Get retrieves a secret by key.
	Get(ctx context.Context, key string) (string, error)
	// Set stores a secret.
	Set(ctx context.Context, key, value string) error
	// Delete removes a secret.
	Delete(ctx context.Context, key string) error
	// List returns all secret keys.
	List(ctx context.Context) ([]string, error)
	// Name returns the provider name.
	Name() string
}

// ============================================================
// EnvFileProvider - Local .env file provider (for development)
// ============================================================

// EnvFileProvider manages secrets in a .env file.
type EnvFileProvider struct {
	filePath string
	secrets  map[string]string
}

// NewEnvFileProvider creates a new EnvFileProvider.
func NewEnvFileProvider(filePath string) (*EnvFileProvider, error) {
	p := &EnvFileProvider{
		filePath: filePath,
		secrets:  make(map[string]string),
	}

	if err := p.load(); err != nil {
		return nil, err
	}

	return p, nil
}

func (p *EnvFileProvider) load() error {
	file, err := os.Open(p.filePath)
	if os.IsNotExist(err) {
		// File doesn't exist yet, that's OK
		return nil
	}
	if err != nil {
		return fmt.Errorf("failed to open env file: %w", err)
	}
	defer file.Close()

	scanner := bufio.NewScanner(file)
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}

		parts := strings.SplitN(line, "=", 2)
		if len(parts) != 2 {
			continue
		}

		key := strings.TrimSpace(parts[0])
		value := strings.TrimSpace(parts[1])
		// Remove surrounding quotes
		value = strings.Trim(value, "\"'")

		p.secrets[key] = value
	}

	return scanner.Err()
}

func (p *EnvFileProvider) save() error {
	file, err := os.Create(p.filePath)
	if err != nil {
		return fmt.Errorf("failed to create env file: %w", err)
	}
	defer file.Close()

	// Write header
	fmt.Fprintf(file, "# Auto-generated by rotate-secrets\n")
	fmt.Fprintf(file, "# Generated at: %s\n\n", time.Now().UTC().Format(time.RFC3339))

	// Sort keys for consistent output
	keys := make([]string, 0, len(p.secrets))
	for k := range p.secrets {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	for _, key := range keys {
		fmt.Fprintf(file, "%s=%s\n", key, p.secrets[key])
	}

	return nil
}

func (p *EnvFileProvider) Name() string {
	return "env"
}

func (p *EnvFileProvider) Get(ctx context.Context, key string) (string, error) {
	value, exists := p.secrets[key]
	if !exists {
		return "", ErrSecretNotFound
	}
	return value, nil
}

func (p *EnvFileProvider) Set(ctx context.Context, key, value string) error {
	p.secrets[key] = value
	return p.save()
}

func (p *EnvFileProvider) Delete(ctx context.Context, key string) error {
	if _, exists := p.secrets[key]; !exists {
		return ErrSecretNotFound
	}
	delete(p.secrets, key)
	return p.save()
}

func (p *EnvFileProvider) List(ctx context.Context) ([]string, error) {
	keys := make([]string, 0, len(p.secrets))
	for k := range p.secrets {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys, nil
}

// ============================================================
// AWSSecretsProvider - AWS Secrets Manager provider
// ============================================================

// AWSSecretsConfig holds AWS Secrets Manager configuration.
type AWSSecretsConfig struct {
	Region string
	Prefix string
}

// AWSSecretsProvider manages secrets in AWS Secrets Manager.
type AWSSecretsProvider struct {
	config AWSSecretsConfig
	// In production, this would use the AWS SDK
	// For now, we'll use a simulated interface
}

// NewAWSSecretsProvider creates a new AWS Secrets Manager provider.
func NewAWSSecretsProvider(cfg AWSSecretsConfig) (*AWSSecretsProvider, error) {
	if cfg.Region == "" {
		cfg.Region = "us-east-1"
	}
	if cfg.Prefix == "" {
		cfg.Prefix = "tetracore/"
	}

	return &AWSSecretsProvider{
		config: cfg,
	}, nil
}

func (p *AWSSecretsProvider) Name() string {
	return "aws"
}

func (p *AWSSecretsProvider) Get(ctx context.Context, key string) (string, error) {
	// AWS SDK implementation would go here
	// For now, return not implemented
	return "", fmt.Errorf("AWS Secrets Manager not configured: install AWS SDK")
}

func (p *AWSSecretsProvider) Set(ctx context.Context, key, value string) error {
	return fmt.Errorf("AWS Secrets Manager not configured: install AWS SDK")
}

func (p *AWSSecretsProvider) Delete(ctx context.Context, key string) error {
	return fmt.Errorf("AWS Secrets Manager not configured: install AWS SDK")
}

func (p *AWSSecretsProvider) List(ctx context.Context) ([]string, error) {
	return nil, fmt.Errorf("AWS Secrets Manager not configured: install AWS SDK")
}

// ============================================================
// VaultProvider - HashiCorp Vault provider
// ============================================================

// VaultConfig holds HashiCorp Vault configuration.
type VaultConfig struct {
	URL        string
	Token      string
	MountPoint string
}

// VaultProvider manages secrets in HashiCorp Vault.
type VaultProvider struct {
	config VaultConfig
	// In production, this would use the Vault client
}

// NewVaultProvider creates a new HashiCorp Vault provider.
func NewVaultProvider(cfg VaultConfig) (*VaultProvider, error) {
	if cfg.URL == "" {
		cfg.URL = "http://localhost:8200"
	}
	if cfg.MountPoint == "" {
		cfg.MountPoint = "secret"
	}
	if cfg.Token == "" {
		return nil, fmt.Errorf("VAULT_TOKEN is required")
	}

	return &VaultProvider{
		config: cfg,
	}, nil
}

func (p *VaultProvider) Name() string {
	return "vault"
}

func (p *VaultProvider) Get(ctx context.Context, key string) (string, error) {
	return "", fmt.Errorf("HashiCorp Vault not configured: install vault client")
}

func (p *VaultProvider) Set(ctx context.Context, key, value string) error {
	return fmt.Errorf("HashiCorp Vault not configured: install vault client")
}

func (p *VaultProvider) Delete(ctx context.Context, key string) error {
	return fmt.Errorf("HashiCorp Vault not configured: install vault client")
}

func (p *VaultProvider) List(ctx context.Context) ([]string, error) {
	return nil, fmt.Errorf("HashiCorp Vault not configured: install vault client")
}

// ============================================================
// MemoryProvider - In-memory provider for testing
// ============================================================

// MemoryProvider stores secrets in memory (for testing).
type MemoryProvider struct {
	secrets map[string]string
}

// NewMemoryProvider creates a new in-memory provider.
func NewMemoryProvider() *MemoryProvider {
	return &MemoryProvider{
		secrets: make(map[string]string),
	}
}

func (p *MemoryProvider) Name() string {
	return "memory"
}

func (p *MemoryProvider) Get(ctx context.Context, key string) (string, error) {
	value, exists := p.secrets[key]
	if !exists {
		return "", ErrSecretNotFound
	}
	return value, nil
}

func (p *MemoryProvider) Set(ctx context.Context, key, value string) error {
	p.secrets[key] = value
	return nil
}

func (p *MemoryProvider) Delete(ctx context.Context, key string) error {
	if _, exists := p.secrets[key]; !exists {
		return ErrSecretNotFound
	}
	delete(p.secrets, key)
	return nil
}

func (p *MemoryProvider) List(ctx context.Context) ([]string, error) {
	keys := make([]string, 0, len(p.secrets))
	for k := range p.secrets {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys, nil
}

// ============================================================
// Provider Factory
// ============================================================

// ProviderConfig holds configuration for creating a provider.
type ProviderConfig struct {
	Type string

	// Env provider
	EnvFilePath string

	// AWS provider
	AWSRegion string
	AWSPrefix string

	// Vault provider
	VaultURL        string
	VaultToken      string
	VaultMountPoint string
}

// NewProvider creates a provider based on configuration.
func NewProvider(cfg ProviderConfig) (Provider, error) {
	switch cfg.Type {
	case "env":
		if cfg.EnvFilePath == "" {
			cfg.EnvFilePath = ".env"
		}
		return NewEnvFileProvider(cfg.EnvFilePath)

	case "aws":
		return NewAWSSecretsProvider(AWSSecretsConfig{
			Region: cfg.AWSRegion,
			Prefix: cfg.AWSPrefix,
		})

	case "vault":
		return NewVaultProvider(VaultConfig{
			URL:        cfg.VaultURL,
			Token:      cfg.VaultToken,
			MountPoint: cfg.VaultMountPoint,
		})

	case "memory":
		return NewMemoryProvider(), nil

	default:
		return nil, fmt.Errorf("unknown provider type: %s", cfg.Type)
	}
}

// ============================================================
// Backup structures
// ============================================================

// Backup represents a secret backup entry.
type Backup struct {
	Key       string `json:"key"`
	Value     string `json:"value,omitempty"`
	ValueHash string `json:"value_hash,omitempty"`
	Encrypted bool   `json:"encrypted"`
	Timestamp string `json:"timestamp"`
	Warning   string `json:"warning,omitempty"`
}

// SaveBackup saves a backup to the specified directory.
func SaveBackup(backupDir, key, value string, encrypt bool) error {
	if err := os.MkdirAll(backupDir, 0700); err != nil {
		return fmt.Errorf("failed to create backup directory: %w", err)
	}

	timestamp := time.Now().UTC().Format("20060102_150405")
	filename := filepath.Join(backupDir, fmt.Sprintf("%s_%s.bak", key, timestamp))

	backup := Backup{
		Key:       key,
		Timestamp: timestamp,
		Encrypted: false,
	}

	// For security, only store hash unless encryption is enabled
	if encrypt {
		// Would use actual encryption here
		backup.Value = value
		backup.Encrypted = true
	} else {
		backup.ValueHash = hashValue(value)
		backup.Warning = "Value not stored - only hash available"
	}

	data, err := json.MarshalIndent(backup, "", "  ")
	if err != nil {
		return fmt.Errorf("failed to marshal backup: %w", err)
	}

	if err := os.WriteFile(filename, data, 0600); err != nil {
		return fmt.Errorf("failed to write backup file: %w", err)
	}

	return nil
}

func hashValue(value string) string {
	// Simple hash for demonstration
	// In production, use crypto/sha256
	hash := uint64(0)
	for _, c := range value {
		hash = hash*31 + uint64(c)
	}
	return fmt.Sprintf("%016x", hash)
}
